"""Render the profile and original data artwork entirely offline (stdlib only)."""
from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime
from html import escape
import json
import math
from pathlib import Path
import sys
from urllib.parse import urlparse
import xml.etree.ElementTree as ET

from render_identity import render_identity, THEMES
from update_profile import validate_snapshot

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = """<!--
THESIS: A builder's terminal opens onto real, inspectable work. Projects carry the story.
OWN-WORLD: Graphite and warm paper, moss-green signal paths, strong lettering and plain-language project notes.
STORY: Meet Arnav, inspect three working projects, follow their source and recent releases.
FIRST VIEWPORT: Full-width original identity, a compact introduction and direct links, then the first project. Mobile recomposes the artwork.
FORM: Developer terminal with original branching geometry.
Generated by scripts/render_profile.py. Edit profile.config.json; do not edit generated content.
-->"""


def safe_url(value: str) -> str:
    url = urlparse(value)
    if url.scheme != "https" or not url.netloc or url.username or url.password:
        raise ValueError("Public links must be credential-free HTTPS URLs")
    return escape(value, quote=True)


def link(label: str, url: str) -> str:
    if len(label) > 1 and label[-2] == " " and label[-1] in "↗↓→↑":
        label = label[:-2] + "\u00a0" + label[-1]
    return f'<a href="{safe_url(url)}">{escape(label)}</a>'


def picture(stem: str, alt: str, mobile: bool = False) -> str:
    sources = []
    if mobile:
        sources += [
            f'  <source media="(max-width: 600px) and (prefers-color-scheme: dark)" srcset="assets/generated/{stem}-mobile-dark.svg">',
            f'  <source media="(max-width: 600px)" srcset="assets/generated/{stem}-mobile-light.svg">',
        ]
    sources += [f'  <source media="(prefers-color-scheme: dark)" srcset="assets/generated/{stem}-dark.svg">']
    return '<picture>\n' + '\n'.join(sources) + f'\n  <img src="assets/generated/{stem}-light.svg" width="1200" alt="{escape(alt, quote=True)}">\n</picture>'


def iso_date(value: str) -> str:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).strftime("%d %b %Y")


def work_distribution(snapshot: dict) -> tuple[list[dict], list[tuple[str, int]]]:
    """One shared grouping for visual nodes and the image's accessible description."""
    repos = [r for r in snapshot["repositories"] if not r.get("fork") and not r.get("archived")
             and r["name"].lower() != snapshot["username"].lower()]
    counts = Counter(r.get("language") or "Other" for r in repos)
    groups = counts.most_common(3)
    remaining = sum(count for _, count in counts.most_common()[3:])
    if remaining:
        groups.append(("Other languages", remaining))
    return repos, groups


def work_map(snapshot: dict, mode: str, mobile: bool = False) -> str:
    """Actual repository nodes, grouped by their primary language. No inferred activity."""
    t = THEMES[mode]
    repos, groups = work_distribution(snapshot)
    rows = max((math.ceil(n / 12) for _, n in groups), default=1)
    row_height = max(170, 118 + rows * 19)
    width, height = (640, 155 + math.ceil(len(groups) / 2) * row_height) if mobile else (1200, max(290, 225 + rows * 19))
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="map-title map-desc">',
             '<title id="map-title">The shape of my public work</title>',
             f'<desc id="map-desc">{len(repos)} public non-fork, non-archived repositories, grouped by primary language: {escape(", ".join(f"{k}: {v}" for k,v in groups))}. Each small node is one repository. This measures repository distribution, not proficiency.</desc>',
             f'<rect width="{width}" height="{height}" rx="8" fill="{t["bg"]}"/>',
             '<style>text{font-family:Consolas,"Liberation Mono",monospace}</style>',
             f'<text x="32" y="40" font-size="{26 if mobile else 20}" fill="{t["text"]}">The shape of my public work</text>',
             f'<text x="32" y="73" font-size="{18 if mobile else 14}" fill="{t["muted"]}">One node, one repository.</text>']
    for i, (language, count) in enumerate(groups):
        if mobile:
            x, y = 34 + (i % 2) * 298, 140 + (i // 2) * row_height
        else:
            x, y = 34 + i * 295, 125
        parts.append(f'<path d="M{x} {y+8}V{y+62}H{x+235}" fill="none" stroke="{t["muted"]}" stroke-opacity=".32"/>')
        parts.append(f'<text x="{x}" y="{y}" fill="{t["text"]}" font-size="{22 if mobile else 19}">{escape(language)}</text>')
        parts.append(f'<text x="{x}" y="{y+29}" fill="{t["muted"]}" font-size="{18 if mobile else 14}">{count} {"repository" if count==1 else "repositories"}</text>')
        for n in range(count):
            col, row = n % 12, n // 12
            cx, cy = x + 14 + col * 19, y + 62 + row * 19
            parts.append(f'<circle cx="{cx}" cy="{cy}" r="4" fill="{t["accent"]}"/>')
    foot_y = height - 28
    footer = 'Public work · forks and archives excluded' if mobile else 'Primary language · public repositories · forks and archives excluded'
    parts.append(f'<text x="32" y="{foot_y}" fill="{t["muted"]}" font-size="{15 if mobile else 12}">{footer}</text>')
    parts.append('</svg>')
    return "\n".join(parts)


def render_readme(config: dict, snapshot: dict) -> str:
    username = config["username"]
    github = f"https://github.com/{username}"
    parts = [CONTRACT, picture("hero", f'{config["name"]} — {config["tagline"]} Focus: {config["focus"]}.', True),
             '<p><strong>I build practical AI systems and interactive web experiences.</strong><br>',
             'Local models, visual infrastructure, and the occasional idea that grows into a tree.</p>',
             '<p>' + ' &nbsp; / &nbsp; '.join([link("Portfolio ↗", config["links"]["portfolio"]), '<a href="#selected-work">Selected work&nbsp;↓</a>', link("All repositories ↗", github+"?tab=repositories")]) + '</p>',
             '<h2>Selected work</h2>']
    for p in config["projects"]:
        image = p["image"]
        if not image.startswith("assets/projects/") or ".." in image or not (ROOT/image).is_file():
            raise ValueError("Project image must exist inside assets/projects")
        target = p.get("demo_url") or p["repo_url"]
        screenshot = f'<img src="{escape(image,quote=True)}" width="1200" alt="{escape(p["alt"],quote=True)}">'
        if p.get('animation'):
            animation = p['animation']
            if not animation.startswith('assets/projects/') or '..' in animation or not (ROOT/animation).is_file():
                raise ValueError('Project animation must exist inside assets/projects')
            screenshot = '<picture><source media="(prefers-reduced-motion: reduce)" srcset="'+escape(image,quote=True)+'">'+screenshot.replace(escape(image,quote=True),escape(animation,quote=True))+'</picture>'
        parts += [f'<h3>{escape(p["title"])} — {escape(p["subtitle"])}</h3>',
                  f'<a href="{safe_url(target)}">{screenshot}</a>',
                  f'<p>{escape(p["description"])}</p>',
                  '<p>' + ' &nbsp; '.join(f'<code>{escape(s)}</code>' for s in p["stack"]) + '</p>']
        actions = [link("Explore the code ↗", p["repo_url"])]
        if p.get("demo_url"):
            actions.insert(0, link("Open the demo ↗", p["demo_url"]))
        if p.get("release_url"):
            actions.append(link("Get the release ↗", p["release_url"]))
        parts += ['<p>' + ' &nbsp; · &nbsp; '.join(actions) + '</p>']
        if p.get("note"):
            parts += [f'<p><sub>{escape(p["note"])}</sub></p>']
        parts.append('<br>')

    parts += ['<h2>From the workbench</h2>']
    release_repos = set()
    releases = []
    for r in snapshot.get("releases", []):
        if r["repo"] not in release_repos:
            release_repos.add(r["repo"])
            releases.append(r)
    if releases:
        parts += ['<p><strong>Latest releases</strong></p>', '<ul>']
        for r in releases[:3]:
            label = f'{r["repo"].split("/")[-1]} / {r["tag"]}'
            parts += [f'<li>{link(label, r["url"])} — {iso_date(r["published_at"])}</li>']
        parts += ['</ul>']
    activity = snapshot.get("activity", [])
    seen, unique = set(), []
    for item in activity:
        if item["repo"] not in seen:
            seen.add(item["repo"])
            unique.append(item)
    if unique:
        parts += ['<p><strong>Recent public activity</strong></p>', '<ul>']
        for item in unique[:3]:
            label = f'{item["repo"].split("/")[-1]} — {item["title"]}'
            parts += [f'<li>{link(label,item["url"])} <sub>({iso_date(item["date"])})</sub></li>']
        parts += ['</ul>']
    if not releases and not unique:
        parts += ['<p>' + link("See what I’m working on →",github+"?tab=repositories") + '</p>']
    if snapshot.get("updated_at"):
        parts += [f'<p><sub>Last refreshed {iso_date(snapshot["updated_at"])} · from public GitHub activity.</sub></p>']

    if snapshot["repositories"]:
        repositories, groups = work_distribution(snapshot)
        distribution = ", ".join(f"{language}: {count}" for language, count in groups)
        alt = (f"{len(repositories)} public repositories by primary language: {distribution}. "
               "One node per repository. Forks, archives, and this profile repository excluded. "
               "Repository distribution, not proficiency.")
        parts += [picture("work-map", alt, True)]
    parts += ['<details>', '<summary>A few more things I’ve built</summary>',
              '<br>', '<ul>',
              '<li>' + link("HSN Classifier",github+"/HSN-Classifier-LLM") + ' — product classification with retrieval-augmented generation.</li>',
              '<li>' + link("Task Tracker",github+"/task-tracker") + ' — a full-stack task app with Next.js, Express, MongoDB, and Redis.</li>',
              '<li>' + link("Zillow Medallion",github+"/zillow-medallion-databricks") + ' — data engineering with Databricks.</li>',
              '</ul>', '</details>', '<br>', '<hr>',
              '<p><strong>Have something interesting in mind?</strong><br>' + link("Find me at arnavbule.in ↗",config["links"]["portfolio"]) + ' &nbsp; · &nbsp; ' + link("Explore my GitHub ↗",github) + '</p>']
    return "\n\n".join(parts) + "\n"


def render_all(config: dict, snapshot: dict) -> dict[Path,str]:
    validate_snapshot(snapshot, config["username"])
    generated = {ROOT/'assets/generated'/name: svg+'\n' for name,svg in render_identity(config).items()}
    for mobile in (False,True):
        for theme in THEMES:
            name = f'work-map{"-mobile" if mobile else ""}-{theme}.svg'
            generated[ROOT/'assets/generated'/name] = work_map(snapshot,theme,mobile)+'\n'
    for path, content in generated.items():
        ET.fromstring(content)
        if '<script' in content.lower() or 'foreignObject' in content:
            raise ValueError("Generated SVG must be self-contained and script-free")
    generated[ROOT/'README.md'] = render_readme(config,snapshot)
    return generated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true',help='Check generated files match their inputs without writing')
    args = parser.parse_args()
    config = json.loads((ROOT/'profile.config.json').read_text(encoding='utf-8'))
    snapshot = json.loads((ROOT/'data/activity.json').read_text(encoding='utf-8'))
    outputs = render_all(config,snapshot)
    stale = []
    for path,content in outputs.items():
        existing = path.read_text(encoding='utf-8') if path.exists() else None
        if existing != content:
            if args.check:
                stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True,exist_ok=True)
                temporary = path.with_suffix(path.suffix+'.tmp')
                temporary.write_text(content,encoding='utf-8',newline='\n')
                temporary.replace(path)
    if stale:
        print('Generated files need refreshing: '+', '.join(stale),file=sys.stderr)
        return 1
    print(f'{"Verified" if args.check else "Rendered"} README and {len(outputs)-1} original SVG assets.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
